### User Service
GET http://localhost:8081/api/users/1001

### Order Service
GET http://localhost:8082/api/orders/5001

### Gateway -> User Service
GET http://localhost:8080/api/users/1001

### Gateway -> Order Service
GET http://localhost:8080/api/orders/5001

### Missing user
GET http://localhost:8081/api/users/9999

### Missing order
GET http://localhost:8082/api/orders/9999
